---
# http://docs.travis-ci.com/user/languages/go/#Default-Test-Script
language: go
go: # https://github.com/atotto/travisci-golang-example
- '1.7'
- '1.8'
- stable
- master
#env:
#  matrix:
#  - GOOS=linux
#  - GOOS=darwin
#  - GOOS=freebsd
#  - GOOS=windows
matrix:
  allow_failures:
  - go: '1.7'
  - go: master
branches:
  only: [master, develop]
install:
- go get github.com/gorilla/sessions
- go get github.com/jteeuwen/go-bindata/...
- go get github.com/yhat/scrape
- go get golang.org/x/crypto/bcrypt
- go get golang.org/x/net/html
- go get golang.org/x/net/html/atom
- go get golang.org/x/text/language
- go get golang.org/x/text/search
- go get gopkg.in/yaml.v2
  # for testing only:
- go get github.com/stretchr/testify
- go get golang.org/x/tools/blog/atom
script:
- go-bindata -ignore=.DS_Store -prefix static static/...
- go vet -x
- go test -v
